name: Update README

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  update-latest-blog:
    name: Update latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in realtong.cn posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.realtong.cn/rss.xml"
